# Generated by Django 3.1.7 on 2021-03-22 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Resim')),
                ('description', models.TextField(verbose_name='İçerik')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Resim')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
            ],
            options={
                'verbose_name_plural': 'Hakkımızda',
            },
        ),
        migrations.CreateModel(
            name='BrandsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='başlık')),
                ('image', models.ImageField(null=True, upload_to='brands', verbose_name='Resim')),
                ('number', models.IntegerField(verbose_name='Numara')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
            ],
            options={
                'verbose_name_plural': 'Markalazımız',
            },
        ),
        migrations.CreateModel(
            name='GalleryModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='başlık')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery', verbose_name='Resim')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
            ],
            options={
                'verbose_name_plural': 'Galeri',
            },
        ),
        migrations.CreateModel(
            name='HomeModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('slider', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Resim')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('number', models.IntegerField(verbose_name='Numara')),
            ],
            options={
                'verbose_name_plural': 'Slider Ayarları',
            },
        ),
        migrations.CreateModel(
            name='StoreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('adres', models.CharField(max_length=255, verbose_name='Adres')),
                ('telefon', models.CharField(max_length=255, verbose_name='Telefon')),
                ('email', models.CharField(max_length=255, verbose_name='Email Adresi')),
                ('calisma_saatleri', models.CharField(max_length=255)),
                ('maps', models.CharField(max_length=255, verbose_name='Harita')),
            ],
            options={
                'verbose_name_plural': 'Mağazalar',
            },
        ),
        migrations.CreateModel(
            name='TechnologyDesModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='İçerik')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='Data Published')),
            ],
            options={
                'verbose_name_plural': 'Teknoloji İçerik',
            },
        ),
        migrations.CreateModel(
            name='TechnologyModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery', verbose_name='Resim')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
            ],
            options={
                'verbose_name_plural': 'Teknoloji Resimleri',
            },
        ),
        migrations.CreateModel(
            name='StoreGalleryModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('image', models.ImageField(blank=True, null=True, upload_to='store', verbose_name='Resim')),
                ('magaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glasses.storemodel', verbose_name='Mağaza')),
            ],
            options={
                'verbose_name_plural': 'Mağaza Resimleri',
            },
        ),
    ]
